# -*- coding: utf-8 -*-


from PySide import QtCore, QtGui
from SimNDT.gui.constants import *

class Ui_addEllipseDialog(object):
    def setupUi(self, addEllipseDialog):
        scaleUI = SCALE_UI
        addEllipseDialog.setObjectName("addEllipseDialog")
        addEllipseDialog.setWindowModality(QtCore.Qt.WindowModal)
        addEllipseDialog.resize(254*scaleUI, 258*scaleUI)
        addEllipseDialog.setMinimumSize(QtCore.QSize(254*scaleUI, 258*scaleUI))
        addEllipseDialog.setMaximumSize(QtCore.QSize(254*scaleUI, 258*scaleUI))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ellipse.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        addEllipseDialog.setWindowIcon(icon)
        addEllipseDialog.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        addEllipseDialog.setSizeGripEnabled(False)
        addEllipseDialog.setModal(False)
        self.buttonBox = QtGui.QDialogButtonBox(addEllipseDialog)
        self.buttonBox.setGeometry(QtCore.QRect(50*scaleUI, 220*scaleUI, 191*scaleUI, 32*scaleUI))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayoutWidget = QtGui.QWidget(addEllipseDialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(9*scaleUI, 19*scaleUI, 233*scaleUI, 181*scaleUI))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.formLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.centerXLabel = QtGui.QLabel(self.formLayoutWidget)
        self.centerXLabel.setObjectName("centerXLabel")
        self.gridLayout.addWidget(self.centerXLabel, 0, 0, 1, 1)
        self.centerXLineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.centerXLineEdit.setMinimumSize(QtCore.QSize(80*scaleUI, 0))
        self.centerXLineEdit.setMaximumSize(QtCore.QSize(80*scaleUI, 21*scaleUI))
        self.centerXLineEdit.setObjectName("centerXLineEdit")
        self.gridLayout.addWidget(self.centerXLineEdit, 0, 1, 1, 1)
        self.centerYLabel = QtGui.QLabel(self.formLayoutWidget)
        self.centerYLabel.setObjectName("centerYLabel")
        self.gridLayout.addWidget(self.centerYLabel, 1, 0, 1, 1)
        self.centerYLineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.centerYLineEdit.setMinimumSize(QtCore.QSize(80*scaleUI, 0))
        self.centerYLineEdit.setMaximumSize(QtCore.QSize(80*scaleUI, 16777215))
        self.centerYLineEdit.setObjectName("centerYLineEdit")
        self.gridLayout.addWidget(self.centerYLineEdit, 1, 1, 1, 1)
        self.semiMajorAxisLabel = QtGui.QLabel(self.formLayoutWidget)
        self.semiMajorAxisLabel.setObjectName("semiMajorAxisLabel")
        self.gridLayout.addWidget(self.semiMajorAxisLabel, 2, 0, 1, 1)
        self.semiMajorAxisLineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.semiMajorAxisLineEdit.setMinimumSize(QtCore.QSize(80*scaleUI, 0))
        self.semiMajorAxisLineEdit.setMaximumSize(QtCore.QSize(80*scaleUI, 16777215))
        self.semiMajorAxisLineEdit.setObjectName("semiMajorAxisLineEdit")
        self.gridLayout.addWidget(self.semiMajorAxisLineEdit, 2, 1, 1, 1)
        self.semiMinorAxisLabel = QtGui.QLabel(self.formLayoutWidget)
        self.semiMinorAxisLabel.setObjectName("semiMinorAxisLabel")
        self.gridLayout.addWidget(self.semiMinorAxisLabel, 3, 0, 1, 1)
        self.semiMinorAxisLineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.semiMinorAxisLineEdit.setMinimumSize(QtCore.QSize(80*scaleUI, 0))
        self.semiMinorAxisLineEdit.setMaximumSize(QtCore.QSize(80*scaleUI, 16777215))
        self.semiMinorAxisLineEdit.setObjectName("semiMinorAxisLineEdit")
        self.gridLayout.addWidget(self.semiMinorAxisLineEdit, 3, 1, 1, 1)
        self.angleLabel = QtGui.QLabel(self.formLayoutWidget)
        self.angleLabel.setObjectName("angleLabel")
        self.gridLayout.addWidget(self.angleLabel, 4, 0, 1, 1)
        self.angleLineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.angleLineEdit.setMinimumSize(QtCore.QSize(80*scaleUI, 0))
        self.angleLineEdit.setMaximumSize(QtCore.QSize(80*scaleUI, 16777215))
        self.angleLineEdit.setObjectName("angleLineEdit")
        self.gridLayout.addWidget(self.angleLineEdit, 4, 1, 1, 1)
        self.labelLabel = QtGui.QLabel(self.formLayoutWidget)
        self.labelLabel.setObjectName("labelLabel")
        self.gridLayout.addWidget(self.labelLabel, 5, 0, 1, 1)
        self.labelSpinBox = QtGui.QSpinBox(self.formLayoutWidget)
        self.labelSpinBox.setMaximum(240)
        self.labelSpinBox.setSingleStep(40)
        self.labelSpinBox.setObjectName("labelSpinBox")
        self.gridLayout.addWidget(self.labelSpinBox, 5, 1, 1, 1)

        self.retranslateUi(addEllipseDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), addEllipseDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), addEllipseDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(addEllipseDialog)

    def retranslateUi(self, addEllipseDialog):
        addEllipseDialog.setWindowTitle(QtGui.QApplication.translate("addEllipseDialog", "Add Ellipse", None, QtGui.QApplication.UnicodeUTF8))
        addEllipseDialog.setToolTip(QtGui.QApplication.translate("addEllipseDialog", "Add Ellipse", None, QtGui.QApplication.UnicodeUTF8))
        addEllipseDialog.setStatusTip(QtGui.QApplication.translate("addEllipseDialog", "Add Elipse", None, QtGui.QApplication.UnicodeUTF8))
        self.centerXLabel.setText(QtGui.QApplication.translate("addEllipseDialog", "Center X (mm)", None, QtGui.QApplication.UnicodeUTF8))
        self.centerYLabel.setText(QtGui.QApplication.translate("addEllipseDialog", "Center Y (mm)", None, QtGui.QApplication.UnicodeUTF8))
        self.semiMajorAxisLabel.setText(QtGui.QApplication.translate("addEllipseDialog", "Semi-Major Axis (mm)", None, QtGui.QApplication.UnicodeUTF8))
        self.semiMinorAxisLabel.setText(QtGui.QApplication.translate("addEllipseDialog", "Semi-Minor Axis (mm)", None, QtGui.QApplication.UnicodeUTF8))
        self.angleLabel.setText(QtGui.QApplication.translate("addEllipseDialog", "Angle", None, QtGui.QApplication.UnicodeUTF8))
        self.labelLabel.setText(QtGui.QApplication.translate("addEllipseDialog", "Label", None, QtGui.QApplication.UnicodeUTF8))

